### ISSUE TITLE
Understanding unload / beforeUnload data collection w.r.t boomerang!

### ISSUE THREAD

**Issue by samarpanda** [SOASTA/boomerang#101]
You guys have developed a wonderful product. I thank all of you who have developed / contributed to this product.

I have few questions, especially wondering about this [https://github.com/SOASTA/boomerang/blob/master/boomerang.js#L999-L1030](https://github.com/SOASTA/boomerang/blob/master/boomerang.js#L999-L1030)
1. Do we see any performance bottleneck using `beforeunload` / `unload`? 
2. In case of latency, this data submission will take longer than usual scenarios. Are we holding this connection before user moves out of the page?
3. Logically speaking as user is navigating to different page we could collect data in the next page. Please correct me if i am wrong here.
4. Is it an anti-pattern to collect this data on `before-unload` ?

Used chrome devtools to evaluate this specific scenario. It seems although request for next page gets started. But we do wait for the complete operation to be completed ie `beforeunload` beacon log.

**Comment by andreas-marschke** [comment]
Hey @samarpanda !

Unfortunately due to the way unload is implemented in most browsers it is not guaranteed that you get an unload beacon. It is definitely better to either send a beacon on load or trigger a manual beacon during runtime of the page (SPA).

If we _can_ get unload it is best to use it for calculating session time none of the other values on that beacon are necessarily trustworthy as such.

**Comment by bluesmoon** [comment]
> Do we see any performance bottleneck using beforeunload / unload?

Generally no. The browser does not wait for the beacon to go out. If we are
lucky, the beacon is sent, if not, it is lost. Either way the browser will
not allow down the page in order to send the unload beacon.

> In case of latency, this data submission will take longer than usual
scenarios. Are we holding this connection before user moves out of the page?

No, we fire and forget and hope it works.

> Logically speaking as user is navigating to different page we could
collect data in the next page. Please correct me if i am wrong here.

We cannot do this as the previous page's browsing context is lost when the
navigation completes.

> Is it an anti-pattern to collect this data on before-unload ?

There are no patterns here as the web is extremely unreliable and browsers
do not all agree on a standard. A better option might be too use
pageVisibility, and that's something we're investigating, but it's not
without its own caveats.

**Comment by samarpanda** [comment]
@bluesmoon Can you suggest sites using boomerang? Would like to profile there sites w.r.t boomerang usage.

**Comment by bluesmoon** [comment]
Use datanyze to find sites that use boomerang.

**Comment by samarpanda** [comment]
@andreas-marschke Yes, agree with you. But i am afraid they are not only sending session time.

**Comment by samarpanda** [comment]
Tested for one of the site using boomerang. What i tried is reloading the page. Below is what i saw using timeline chrome devtools: 

| Reload Page     | Event (beforeunload) | Page Request Started  |
| :------- | ----: | :---: | :---: |
| clicking on a link | Function Call (Handler) | Boomerang log tracking (237ms)     |
|     | 256ms   |  419ms   |

Seems like `beforeunload` is blocking the page request to start.

**Comment by andreas-marschke** [comment]
@samarpanda again, every implementation is different. Just from what you see in a most recent chrome developer tools might not be what is actually happening on the page itself or in the browsers internals.

And yes we are sending more on our boomerang beacon since `impl.vars` in `boomerang.js` is still populated from initial page load and runtime. But what I meant was that we at SOASTA if at all and if the rest of the data makes sense will only really care about the session duration you could possibly extract from an unload beacon

**Comment by samarpanda** [comment]
>Just from what you see in a most recent chrome developer tools might not be what is actually happening on the page itself or in the browsers internals.

Is this possible? I thought chrome devtools to show exactly what's happening with the code. Could you point me to some examples, where chrome devtools not showing exactly what's happening behind?

**Comment by bluesmoon** [comment]
It shows what's happening in your browser, not on every user's browser.

**Comment by nicjansma** [comment]
@samarpanda The main difference between `beforeunload` and `unload` is that `beforeunload` handlers can block the navigation to the next page, so are executed serially within the current browsing context and the browser waits for them to complete before navigating.

Unfortunately iOS does not currently support `beforeunload`.

Boomerang hooks into both, using whichever one fires first.  Boomerang attempts to send an unload beacon out at this point, though as the others have mentioned, it is not guaranteed it will send its payload before the browsing context has navigated to the next page.  We find it more reliably sent in browsers that support `beforeunload`.

We attempt to do as little work as possible in the unload handler, as we don't want to affect the user's navigating.

Do you have specific concerns about any of the work Boomerang is doing in the `unload` / `beforeunload`?  With the timeline you shared above, did you limit your investigation to a page that _only_ has Boomerang hooking into the `beforeunload`? (many scripts do).  When profiling in the past, we've generally found Boomerang to only add a few milliseconds to the handler.
