### ISSUE TITLE
Is boomerang published on npm?

### ISSUE THREAD

**Issue by mickaeltr** [SOASTA/boomerang#108]
Thanks :)

**Comment by bluesmoon** [comment]
It's not.  We actually don't have releases.  The expectation is that you'd get the source and do `npm install` to pull in dependencies.

**Comment by ruslanmogilevskiy** [comment]
Just added Boomerang to npm - https://www.npmjs.com/package/boomerangjs

**Comment by nicjansma** [comment]
@ruslanmogilevskiy We had intentionally not added it to NPM so far, as we have not (yet) been producing "official" builds with "official" version numbers.  Part of the reason is we didn't think there was a good "default" set of plugins to include, as everyone will have different needs.

However, since we have a Bower package, it's probably a good thing to have a NPM package too, so there isn't confusion.  Thank you for creating the package.  Would you be able to add myself, @bluesmoon, @andreas-marschke and @querymetrics as admins for the repository?

**Comment by bluesmoon** [comment]
@ruslanmogilevskiy, you'll need to keep it updated on every commit since the dev team cannot support the npm package
