### ISSUE TITLE
Error when importing Boomerang using strict mode

### ISSUE THREAD

**Issue by LaurentMox** [SOASTA/boomerang#117]
Hi everyone !

When importing Boomerang using strict mode (because of ES6+ import syntax) i got this following exception:
```javascript
import '../lib/boomerang-js/boomerang-1.0.1481536883-debug.js';
```

> ./app/lib/boomerang-js/boomerang-1.0.1481536883-debug.js
> Module build failed: SyntaxError: Deleting local variable in strict mode (1618:1)
> 
>   1616 | 	};
>   1617 |
>  1618 | 	delete BOOMR_start;
>             | 	^
>   1619 |
>   1620 | 	if (typeof BOOMR_lstart === "number") {
>   1621 | 		boomr.t_lstart = BOOMR_lstart;
> 
> BabelLoaderError: SyntaxError: Deleting local variable in strict mode (1618:1)
> 
>   1616 | 	};
>   1617 |
>  1618 | 	delete BOOMR_start;
>        | 	^
>   1619 |
>   1620 | 	if (typeof BOOMR_lstart === "number") {
>   1621 | 		boomr.t_lstart = BOOMR_lstart;
> at transpile (/home/laurent/devs/myProject/node_modules/babel-loader/lib/index.js:55:13)
>     at Object.module.exports (/home/laurent/devs/myProject/node_modules/babel-loader/lib/index.js:138:12)
>  @ ./app/app.js 31:0-64

It looks like the exception is resolved when replacing "BOOMR_start" with "window.BOOMR_start"
Same issue with "BOOMR_lstart"

I also had to restore the module loaders for error-stack-parser (see your comments "Via https://github.com/stacktracejs/error-stack-parser" around line 14 in errors.js) to prevent another error.

Thanks !

**Comment by andreas-marschke** [comment]
Due to our commitment backward compatibility we will not remove this line as we want to pollute the  global namespace as minimally as possible. We are also currently not pursuing being importable as an ES6 module as this is simply not what Boomerang was designed for.

Your best choice is to host boomerang as a compiled build with what ever plugins you intend to use separately from your overall application and use the asynchronous loader described in the readme to load boomerang and measure your pages performance.

**Comment by bluesmoon** [comment]
@LaurentMox to be clear, changing the code from `delete BOOMR_start` to `delete window.BOOMR_start` will cause an exception to be thrown on IE8. Unfortunately ES6 is not backwards compatible with browser bugs, and as a 3rd party library, we need to be compatible with bugs in browsers, frameworks, and sites.
