### ISSUE TITLE
AngularJS2 support

### ISSUE THREAD

**Issue by akamanocha** [SOASTA/boomerang#120]
Pardon me if its stupid question.
Is the boomerang angularjs plugin support meant for angularjs2 also? Or anything in work?

**Comment by nicjansma** [comment]
AngularJS2 no longer supports the [`$routeChangeStart`](https://docs.angularjs.org/api/ngRoute/service/$route) event that our [`angular.js plugin`](https://github.com/SOASTA/boomerang/blob/master/plugins/angular.js) hooks into, so that plugin will not work with AngularJS 2.  It looks like AngularJS 2 has a [completely different](https://angular.io/docs/ts/latest/api/router/index/Event-type-alias.html) route system and notifications.

However, the [`history.js plugin`](https://github.com/SOASTA/boomerang/blob/master/plugins/history.js) plugin was written to work with any SPA that uses the `window.History` object to change the URL, which AngularJS 2 does.  So you should be able to give the History plugin a try (set `auto=true`).

We haven't extensively tested `history.js` with Angular2, but a quick test of the https://github.com/mgechev/angular-seed suggests the `history.js` plugin will work fine.
