### ISSUE TITLE
Is it possible to get Session/Geographic/Device details using Boomerang ?

### ISSUE THREAD

**Issue by sivapavi** [SOASTA/boomerang#137]
Hi @nicjansma @andreas-marschke 

Is it possible to get the below mentioned information's  using boomerang plugins ?

1. Session details for SPA websites ? 
2. Geographical locations details (From which location the site is accessed by user ) ?
3. Device details ( The web pages are used by user through which device like (desktop/mobile/tab ) ?

Is there any plugins already available to get those details Or do we need to write any custom script to get ? 

If is it possible , What is the exact parameter name to get those things from generated beacon request ?

Could you please help me to get the details !

Thanks
Siva P

**Comment by andreas-marschke** [comment]
Hey Siva!

1. Yes you have the ability to keep session details with `plugins/rt.js` since that provides you with session data creation/handling via cookies
2. You can achieve that by using the IP of the client mostly. There are ways to do that if you add a plugin that calls back to your server and responds with the IP it sees the request it came with. _Be forewarned though that transmission of this kind may be impacted by data privacy laws in regions such as the EU._
3. You can figure that out based on the User agent details. I leave it as an exercise to you how to handle this. 

Have a read in `plugins/rt.js` for how Boomerang handles sessions.

It is entirely conceivable that Boomerang is not a one-stop solution for everything you may need in your application. So having an understanding of how it works and learning it's internals helps you get there and fill in what you need
