### ISSUE TITLE
State change events are deprecated on Angular UI-Router 1.0 

### ISSUE THREAD

**Issue by mosfet1kg** [SOASTA/boomerang#159]
https://github.com/SOASTA/boomerang/blob/e82d38219b0549d5ee2247b145225e5648b19416/plugins/angular.js#L112

It seems that $rootScope.$on doesn't catch `$stateChange*` events on ui router1.0 ...
please refer to the below link...

https://ui-router.github.io/guide/ng1/migrate-to-1_0#state-change-events

**Comment by nicjansma** [comment]
Thanks @mosfet1kg .  We've started migrated users of Angular to use the `History` plugin with `auto:true` configuration enabled.  That tells Boomerang to listen to the `window.history` object for navigation changes instead of Angular lifecycle events.

We've investigated and found that listening to `window.history` is triggered within a few milliseconds of the Angular events, and should be reliable nearly all SPAs.
