### ISSUE TITLE
[restiming plugin] 405 Invalid method `OPTIONS`

### ISSUE THREAD

**Issue by ibarkowski** [SOASTA/boomerang#162]
Hi,
When I use restiming plugin I have an error while sending beacon: 

boomerang.js:1537 **OPTIONS http://127.0.0.1:8090/beacon 405 (Method Not Allowed)**

Without this plugin everything works fine? Am I doing something wrong?

**Comment by ibarkowski** [comment]
It does'nt work only in chrome (63.0.3239.84). In Firefox works ok.

**Comment by bluesmoon** [comment]
This is a CORS feature supported by some browsers where a cross-domain XHR POST that uses a non-standard content-type will result in a preflight OPTIONS request.

There are two options:
1. Your server needs to support the `OPTIONS` method and return an appropriate CORS header. 
2. You could change the content type in boomerang's XHR beacon sending code to `text/plain`

You can see this post for more info on what's happening: https://www.soasta.com/blog/options-web-performance-with-single-page-applications/

**Comment by bluesmoon** [comment]
@nicjansma have we considered making `text/plain` the default and letting the caller override it via config?

**Comment by querymetrics** [comment]
@bluesmoon isn't a POST with `application/x-www-form-urlencoded` considered a "simple" request with respect to CORS? The server could answer with `Access-Control-Allow-Origin: *` to make the browser happy

@ibarkowski , more info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Server-Side_Access_Control

**Comment by bluesmoon** [comment]
If this is a cross domain XHR, it would depend on whether it's using credentials or not.

**Comment by nicjansma** [comment]
@ibarkowski The only difference I would expect from adding the `restiming.js` plugin is that it is likely changing the beacon from a `GET` to a `POST` because the additional `&restiming=...` data [makes it more than the 2000 character GET limit](https://github.com/SOASTA/boomerang/blob/master/boomerang.js#L1774).

I'm surprised that just changing it to a `POST` would mean it's no longer a [Simple Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests).  `POST` and `application/x-www-form-urlencoded` XHRs are allowed.  Could you review the Simple Request definition to see if there's an additional HTTP Request headers that make it not a Simple Request?  Or if you added credentials?

I'll close this for now -- if you think Boomerang should be doing something different, please let us know.
