### ISSUE TITLE
Asynchronous loading patterns

### ISSUE THREAD

**Issue by fbraun** [SOASTA/boomerang#194]
Do the two documented approaches for asynchronous loading (Adding it to the main document / Adding it via an IFRAME) have any advantages over using script elements with an async attribute? Wouldn't the async script tag provide the same capability as the iframe approach with less code (the loading would still start at the same time and would not block the rendering of the page or the load event).

**Comment by AndreyNikiforov** [comment]
the `script async` will behave the same as adding scripts dynamically (all dynamic scripts are `async` by default), which blocks `onload` event and may affect measurements (see https://github.com/SOASTA/boomerang#31-adding-it-to-the-main-document for details). `iframe` approach does not have such observer effect.

**Comment by bluesmoon** [comment]
A very detailed explanation can be found here: http://www.lognormal.com/blog/2012/12/12/the-script-loader-pattern/

You may use `async` as a replacement for method 2 if you're sure all your users use browsers that support the `async` attribute. In reality this means you don't have any users on IE9 or older as all other browsers auto-update.  Since boomerang is supposed to work with IE6+, we still document the method that includes on IE6-9.

FWIW, we're close to releasing a more modern loader that uses preload hints.

**Comment by fbraun** [comment]
Thanks for the details on the differences between the 3 async patterns!
