### ISSUE TITLE
POST requests are not encoded as JSON, with a Content-Type of text/plain as mentioned in the documentation

### ISSUE THREAD

**Issue by sridharangopal** [SOASTA/boomerang#71]
Hi,

I am trying to send the beacon data into HEKA and I assumed that the data sent back from the browser to a beacon server is automatically encoded as JSON data on modern browsers. But on testing it on both Chrome Version 45.0.2454.85 and IE 11.0.9600.17914IS, I only see url-encoded data with content type  application/x-www-form-urlencoded being sent to my Heka backend.

I am assuming that the documentation present here at this location is up to date and is how boomerangjs is supposed to work: 
http://www.lognormal.com/boomerang/doc/api/BOOMR.html

Apologies if this is a know or a closed old issue. I could not find references to this issue on googling around.

**Comment by bluesmoon** [comment]
We did turn that on experimentally, but ended up turning it off because browsers were inconsistent in how they handled the situation, and it made it very complicated to do this in a cross-browser fashion.  Since server side code also has to deal with regular URL encoded data for older browsers, we decided that there was not much benefit to JSON encoding the beacon if it could not be done consistently across all browsers.

Yes, the docs need to be updated.

**Comment by sridharangopal** [comment]
Great. Thanks Phillip. I will go ahead and close this issue if you want me to. Or I can wait until the docs are updated before I close it.

**Comment by bluesmoon** [comment]
I suppose waiting for the docs is a better idea

**Comment by nicjansma** [comment]
Fixed via https://github.com/SOASTA/boomerang/commit/8ae990740f8d03702bb0c93779b33a305e8c807d
