### ISSUE TITLE
Not able to rerun Boomerang

### ISSUE THREAD

**Issue by pytong** [SOASTA/boomerang#78]
What is the recommended way of rerunning Boomerang? I need to rerun the speed test without page refresh if the user has no internet connection the first time Boomerang is run.

I tried to re-init again by running these lines again, but it only runs the first time after BOOMR is inited.

```
BOOMR.init({
	BW: {
		base_url: myImageUrl,
		block_beacon: true
	}
});
```

**Comment by andreas-marschke** [comment]
You can try re-running it by just re-running the BW plugin itself: 

```
BOOMR.plugins.BW.init({ /* your config here */ });
```

Hope this helps?

**Comment by nicjansma** [comment]
Unfortunately there's state that is kept that stops it from re-running if it's already run once.

@pytong: You can add a function similar to this to the `BW` plugin:
```
reRun: function() {
    images.start = 0;
    impl.runs_left = impl.nruns;
    impl.latency_runs = 10;
    impl.results = [];
    impl.latencies = [];
    impl.latency = null;
    impl.complete = impl.aborted = false;

    BOOMR.removeVar("ba", "ba_err", "lat", "lat_err");

    this.run();
}
```

However, you'll then need to figure out what to do with that new data and how to beacon it (since you wouldn't want to duplicate the page load time with this new data).

Let us know if you come to a solution.

**Comment by pytong** [comment]
I haven't tried the suggested ways above since the project was finished months ago. In the end, I implemented similar but simplified logic like Boomerang by following one of the presentations online of Philip Tellis.

**Comment by nicjansma** [comment]
@pytong good to hear you were able to find a solution.
